const px = 20;
const skin = '#dd8275';
const mouth = '#b45844';
const hair = '#8c4c24';

export default {
    settings: {
        shape: 'square',
        size: px,
        color: '#000000',
    },
    list: [
        {pk: 1, hoff: px, voff: 0, blur: 0, spread: 0, color: skin},
        {pk: 2, hoff: -px, voff: 0, blur: 0, spread: 0, color: skin},
        {pk: 3, hoff: -px * 3, voff: 0, blur: 0, spread: 0, color: skin},
        {pk: 4, hoff: -px, voff: -px, blur: 0, spread: 0, color: skin},
        {pk: 5, hoff: 0, voff: -px, blur: 0, spread: 0, color: skin},
        {pk: 6, hoff: px, voff: -px, blur: 0, spread: 0, color: skin},
        {pk: 7, hoff: 0, voff: -px * 2, blur: 0, spread: 0, color: skin},
        {pk: 8, hoff: -px * 4, voff: px, blur: 0, spread: 0, color: skin},
        {pk: 9, hoff: -px * 3, voff: px, blur: 0, spread: 0, color: skin},
        {pk: 10, hoff: -px * 2, voff: px, blur: 0, spread: 0, color: skin},
        {pk: 11, hoff: -px, voff: px, blur: 0, spread: 0, color: skin},
        {pk: 12, hoff: 0, voff: px, blur: 0, spread: 0, color: skin},
        {pk: 13, hoff: px, voff: px, blur: 0, spread: 0, color: skin},
        {pk: 14, hoff: px * 2, voff: px, blur: 0, spread: 0, color: skin},
        {pk: 15, hoff: -px * 4, voff: px * 2, blur: 0, spread: 0, color: skin},
        {pk: 16, hoff: -px * 3, voff: px * 2, blur: 0, spread: 0, color: skin},
        {pk: 17, hoff: -px * 2, voff: px * 2, blur: 0, spread: 0, color: skin},
        {pk: 18, hoff: -px, voff: px * 2, blur: 0, spread: 0, color: skin},
        {pk: 19, hoff: 0, voff: px * 2, blur: 0, spread: 0, color: skin},
        {pk: 20, hoff: px, voff: px * 2, blur: 0, spread: 0, color: skin},
        {pk: 21, hoff: -px * 3, voff: px * 3, blur: 0, spread: 0, color: skin},
        {pk: 22, hoff: -px * 2, voff: px * 3, blur: 0, spread: 0, color: skin},
        {pk: 23, hoff: -px, voff: px * 3, blur: 0, spread: 0, color: skin},
        {pk: 24, hoff: 0, voff: px * 3, blur: 0, spread: 0, color: mouth},
        {pk: 25, hoff: px, voff: px * 3, blur: 0, spread: 0, color: mouth},
        {pk: 26, hoff: -px * 4, voff: px * 4, blur: 0, spread: 0, color: skin},
        {pk: 27, hoff: -px * 3, voff: px * 4, blur: 0, spread: 0, color: skin},
        {pk: 28, hoff: -px * 2, voff: px * 4, blur: 0, spread: 0, color: skin},
        {pk: 29, hoff: -px, voff: px * 4, blur: 0, spread: 0, color: skin},
        {pk: 30, hoff: 0, voff: px * 4, blur: 0, spread: 0, color: skin},
        {pk: 31, hoff: px, voff: px * 4, blur: 0, spread: 0, color: skin},
        {pk: 32, hoff: -px * 4, voff: px * 5, blur: 0, spread: 0, color: skin},
        {pk: 33, hoff: -px * 3, voff: px * 5, blur: 0, spread: 0, color: skin},
        {pk: 34, hoff: -px * 2, voff: -px * 4, blur: 0, spread: px, color: hair},
        {pk: 35, hoff: -px * 5, voff: -px * 2, blur: 0, spread: px, color: hair},
        {pk: 36, hoff: -px * 4, voff: -px * 3, blur: 0, spread: px, color: hair},
        {pk: 37, hoff: -px * 3, voff: -px * 2, blur: 0, spread: px, color: hair},
        {pk: 38, hoff: 0, voff: -px * 4, blur: 0, spread: px, color: hair},
        {pk: 40, hoff: px, voff: -px * 3, blur: 0, spread: px, color: hair},
        {pk: 41, hoff: px * 3, voff: -px * 3, blur: 0, spread: 0, color: hair},
        {pk: 42, hoff: px * 3, voff: -px * 2, blur: 0, spread: 0, color: hair},
        {pk: 43, hoff: -px * 2, voff: 0, blur: 0, spread: 0, color: hair},
        {pk: 44, hoff: -px, voff: -px * 2, blur: 0, spread: 0, color: hair},
        {pk: 45, hoff: px * 2, voff: px * 2, blur: 0, spread: 0, color: hair},
        {pk: 46, hoff: -px * 4, voff: px, blur: 0, spread: px, color: hair},
        {pk: 47, hoff: -px * 7, voff: px * 2, blur: 0, spread: 0, color: hair},
        {pk: 48, hoff: -px * 6, voff: px * 2, blur: 0, spread: 0, color: hair},
        {pk: 49, hoff: -px * 7, voff: px * 3, blur: 0, spread: 0, color: hair},
        {pk: 50, hoff: -px * 6, voff: px * 3, blur: 0, spread: 0, color: hair},
        {pk: 51, hoff: -px * 4, voff: px * 3, blur: 0, spread: 0, color: hair},
        {pk: 52, hoff: -px * 5, voff: px * 3, blur: 0, spread: 0, color: hair},
        {pk: 53, hoff: -px * 2, voff: px * 5, blur: 0, spread: 0, color: hair},
        {pk: 54, hoff: -px, voff: px * 5, blur: 0, spread: 0, color: hair},
    ]
};
